// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rosaowptgkxhibnlvjea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvc2Fvd3B0Z2t4aGlibmx2amVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2MDI4MDcsImV4cCI6MjA4NjE3ODgwN30.wjVGyOPhfRdb6hdh6KBdTn5yDXiuNvwSBHlztq-5US4";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);